import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/component/Navbar";
import { ReduxProvider } from "./redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pokemon",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <Navbar></Navbar>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
